# Generated by Django 4.2.7 on 2024-12-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Camera Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('camera_type', models.CharField(choices=[('fixed', 'Fixed'), ('ptz', 'Pan-Tilt-Zoom'), ('dome', 'Dome')], max_length=20, verbose_name='Camera Type')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('is_recording', models.BooleanField(default=True, verbose_name='Recording Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
        migrations.CreateModel(
            name='SecurityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('security_level', models.CharField(choices=[('high', 'High Security'), ('medium', 'Medium Security'), ('low', 'Low Security')], max_length=20, verbose_name='Security Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cameras', models.ManyToManyField(related_name='zones', to='security.camera')),
            ],
            options={
                'verbose_name': 'Security Zone',
                'verbose_name_plural': 'Security Zones',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Accessed At')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.camera')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
